name: "GitHub Actions Runner - Terraform Apply"

on:
  workflow_dispatch:
    inputs:
      CLIENT_IP:
        type: string
        required: true
        default: "94.134.104.161"
        description: "Client IP"

permissions:
  contents: read

permissions:
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  PLAN_FILE: github-actions-runner.tfplan
  STATE_KEY: ${{ vars.PROJECT_CUSTOMER }}-${{ vars.PROJECT_NAME }}-${{ vars.PROJECT_ENVIRONMENT }}-github-actions-runner.tfstate
  WORKING_DIRECTORY: ./modules/github-actions-runner

jobs:
  terraform_plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          # required for terraform output
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          export TF_CLI_ARGS_init="-backend-config=resource_group_name=${{ vars.STATE_RESOURCE_GROUP_NAME }} -backend-config=storage_account_name=${{ vars.STATE_STORAGE_ACCOUNT_NAME }} -backend-config=container_name=${{ vars.STATE_CONTAINER_NAME }} -backend-config=key=${{ env.STATE_KEY }}"
          terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: |
          export TF_VAR_client_ip='{"name":"ClientIP01","cidr":"${{ inputs.CLIENT_IP }}/32","start_ip_address":"${{ inputs.CLIENT_IP }}","end_ip_address":"${{ inputs.CLIENT_IP }}"}'
          export TF_VAR_client_secret=${{ secrets.CLIENT_SECRET }}
          terraform plan -input=false -var=location=${{ inputs.LOCATION }} -var=client_ip=$TF_VAR_client_ip -out=${{ env.PLAN_FILE }}

      - name: Upload state file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PLAN_FILE }}
          path: ${{ env.WORKING_DIRECTORY }}/${{ env.PLAN_FILE }}
          retention-days: 1

  terraform_apply:
    needs: terraform_plan
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          # required for terraform output
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          export TF_CLI_ARGS_init="-backend-config=resource_group_name=${{ vars.STATE_RESOURCE_GROUP_NAME }} -backend-config=storage_account_name=${{ vars.STATE_STORAGE_ACCOUNT_NAME }} -backend-config=container_name=${{ vars.STATE_CONTAINER_NAME }} -backend-config=key=${{ env.STATE_KEY }}"
          terraform init

      - name: Download state file
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.PLAN_FILE }}
          path: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Show
        run: terraform show ${{ env.PLAN_FILE }}

      - name: Terraform Apply
        run: terraform apply -input=false ${{ env.PLAN_FILE }}
